# Generated by Django 5.1.7 on 2025-07-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sweet_image_url_sweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
