# Generated by Django 5.1.7 on 2025-07-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sweet_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
    ]
